In [1]:
import numpy as np

In [16]:
mat  =[[1,2,3,4,],[5,6,7,8],[1,2,4,5]]
mat = np.array(mat)
print(mat)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 4 5]]


In [17]:
i = np.eye(2)
o = np.ones((3,3))
z = np.zeros((3,3))

i,o,z

(array([[1., 0.],
        [0., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [13]:
a = np.arange(10)
b =np.arange()
a,b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2]))

In [30]:
g =  np.arange(0,100,4)
g = np.reshape(g,(5,5))
ma = g.max() 
mi = g.min()
mai = g.argmax() 
mii = g.argmin()

# g,ma,mi,mai,mii
print(type(g))
sha = g.shape
siz = g.size

sha, siz

<class 'numpy.ndarray'>


((5, 5), 25)