In [1]:
from numpy import array

In [21]:
arr = array([1,2,4,5,56,6,6,67,7,7,7,7,7,765,4,3,2111,2,3])

brodcasting


In [22]:
arr[-3:] = 999
arr

array([  1,   2,   4,   5,  56,   6,   6,  67,   7,   7,   7,   7,   7,
       765,   4,   3, 999, 999, 999])

total changing

In [23]:
arr[:] = 11
arr

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11])

In [25]:
arr = array([1,2,4,5,5,6,6,67,7,7,7,7,7,7,4,3,2,2,3,4])
arr = arr.reshape(4,5)


array([[ 1,  2,  4,  5,  5],
       [ 6,  6, 67,  7,  7],
       [ 7,  7,  7,  7,  4],
       [ 3,  2,  2,  3,  4]])